# Generated by Django 5.0.2 on 2024-02-14 13:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('jmbg', models.CharField(blank=True, max_length=13, validators=[django.core.validators.MaxLengthValidator(limit_value=13, message='JMBG must be 13 characters long'), django.core.validators.MinLengthValidator(limit_value=13, message='JMBG must be 13 characters long'), django.core.validators.RegexValidator('^[0-9]+$', message='JMBG must be a number')])),
                ('gender', models.BooleanField()),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(max_length=18)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('zipcode', models.CharField(blank=True, max_length=10)),
                ('doctor', models.CharField(max_length=50)),
                ('diagnose', models.CharField(max_length=100)),
                ('anestezija', models.BooleanField()),
                ('prijavljen', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reserved_for', models.DateField()),
                ('note', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kontakti.patient')),
            ],
        ),
    ]
