# Generated by Django 4.2.7 on 2024-02-05 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kontakti', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='reserved_for',
            field=models.DateField(),
        ),
    ]
