# Generated by Django 4.2.7 on 2024-02-06 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kontakti', '0002_alter_contact_reserved_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='anestezija',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
