# Generated by Django 4.2.7 on 2024-02-06 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kontakti', '0003_patient_anestezija'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
